deps: update libuv to v1.41.0
v1.41.0
  * unix: report bind error in uv_tcp_connect() (Ben Noordhuis)
  * linux: fix -Wincompatible-pointer-types warning (Ben Noordhuis)
  * linux: fix -Wsign-compare warning (Ben Noordhuis)
  * unix,win: harmonize uv_read_start() error handling (Ben Noordhuis)
  * unix,win: more uv_read_start() argument validation (Ben Noordhuis)
  * stream: add uv_pipe and uv_socketpair to the API (Jameson Nash)
  * unix,win: initialize timer `timeout` field (Ben Noordhuis)
  * fs: fix utime/futime timestamp rounding errors (Ben Noordhuis)
  * unix,fs: fix uv_fs_sendfile() (Santiago Gimeno)
  * unix: fix uv_fs_stat when using statx (Simon Kadisch)
  * linux,macos: fix uv_set_process_title regression (Momtchil Momtchev)
  * unix,fs: on DVS fs, statx returns EOPNOTSUPP (Mark Klein)
  * win, fs: mkdir really return UV_EINVAL for invalid names (Nicholas Vavilov)
  * unix: fix uv_uptime() on linux (schamberg97)
  * unix: check for partial copy_file_range support (Momtchil Momtchev)
  * win: bump minimum supported version to windows 8 (Ben Noordhuis)
  * poll,unix: ensure safety of rapid fd reuse (Bob Weinand)
  * unix: fix uv_uptime() regression (Santiago Gimeno)
  * unix: check for EXDEV in uv__fs_sendfile() (Darshan Sen)
v1.40.0
  * udp: add UV_UDP_MMSG_FREE recv_cb flag (Ryan Liptak)
  * include: re-map UV__EPROTO from 4046 to -4046 (YuMeiJie)
  * win,tty: pass through utf-16 surrogate pairs (Mustafa M)
  * unix: fix DragonFly BSD build (Aleksej Lebedev)
  * win,udp: fix error code returned by connect() (Santiago Gimeno)
  * src: suppress user_timeout maybe-uninitialized (Daniel Bevenius)
  * linux: fix i386 sendmmsg/recvmmsg support (Ben Noordhuis)
  * build: add libuv-static pkg-config file (Nikolay Mitev)
  * unix,win: add uv_timer_get_due_in() (Ulrik Strid)
  * include: remove incorrect UV__ERR() for EPROTO (cjihrig)
v1.39.0
  * unix: use relaxed loads/stores for clock id (Ben Noordhuis)
  * build,win: link to user32.lib and advapi32.lib (George Zhao)
  * unix: squelch harmless valgrind warning (ssrlive)
  * include: fx c++ style comments warnings (Turbinya)
  * linux: use copy_file_range for uv_fs_copyfile when possible (Carter Li)
  * win,tcp: avoid reinserting a pending request (
  * udp: add uv_udp_using_recvmmsg query (Ryan Liptak)
  * include: add internal fields struct to uv_loop_t (Trevor Norris)
  * core: add API to measure event loop idle time (Trevor Norris)
  * win,fs: use CreateDirectoryW instead of _wmkdir (Mustafa M)
  * darwin: use IOKit for uv_cpu_info (Evan Lucas)
  * win,fs: avoid implicit access to _doserrno (Jameson Nash)
  * unix: handle src, dest same in uv_fs_copyfile() (cjihrig)
  * unix: error when uv_setup_args() is not called (Ryan Liptak)
  * fs: clobber req->path on uv_fs_mkstemp() error (tjarlama)
  * cmake: fix compile error C2001 on Chinese Windows (司徒玟琅)
  * tcp: fail instantly if local port is unbound (Bartosz Sosnowski)
  * unix: don't use _POSIX_PATH_MAX (Ben Noordhuis)
v1.38.1
  * win, util: rearrange uv_hrtime (Bartosz Sosnowski)
  * build: link libkvm on netbsd only (Alexander Tokmakov)
  * linux: refactor /proc file reader logic (Ben Noordhuis)
  * linux: read load average from /proc/loadavg (Ben Noordhuis)
  * win: fix visual studio 2008 build (Arenoros)
  * win,tty: fix deadlock caused by inconsistent state (lander0s)
  * unix: use relaxed loads/stores for feature checks (Ben Noordhuis)
  * unix: fix gcc atomics feature check (Ben Noordhuis)
  * darwin: work around clock jumping back in time (Ben Noordhuis)
  * udp: fix write_queue cleanup on sendmmsg error (Santiago Gimeno)
v1.38.0
  * linux: make cpu_times consistently be milliseconds (James Ross)
  * unix,win: add uv_library_shutdown() (Ben Noordhuis)
  * unix: yield cpu when spinlocking on async handle (Ben Noordhuis)
  * win: remove dep on GetQueuedCompletionStatusEx (Colin Finck)
  * win: make uv_udp_init_ex() accept UV_UDP_RECVMMSG (Ben Noordhuis)
  * unix: simplify uv__udp_init_ex() (Ben Noordhuis)
  * win: remove MAX_PATH limitations (Bartosz Sosnowski)
  * build, win: add long path aware manifest (Bartosz Sosnowski)
  * darwin: fix build with non-apple compilers (Ben Noordhuis)
  * win: support environment variables > 32767 chars (Ben Noordhuis)
  * unix: fully initialize struct msghdr (Ben Noordhuis)
  * unix: fix int overflow when copying large files (Michal Artazov)
  * fs: report original error (Bartosz Sosnowski)
  * win, fs: add IO_REPARSE_TAG_APPEXECLINK support (Bartosz Sosnowski)
  * unix: fix memory leak when uv_loop_init() fails (Anna Henningsen)
  * unix: shrink uv_udp_set_source_membership() stack (Ben Noordhuis)
  * unix,win: fix wrong sizeof argument to memcpy() (Ben Noordhuis)
  * build: check for libraries not provided by libc (Jeroen Roovers)
  * unix: don't abort when getrlimit() fails (Ben Noordhuis)
v1.37.0
  * timer: remove redundant check in heap compare (Yash Ladha)
  * udp: add flag to enable recvmmsg(2) explicitly (Saúl Ibarra Corretgé)
v1.36.0
  * udp: return recvmmsg-ed datagrams in order (Saúl Ibarra Corretgé)
  * win: use RtlGenRandom from advapi32.dll directly (Ben Noordhuis)
  * fs: add uv_fs_lutime() (Sk Sajidul Kadir)
  * unix: implement cpu_relax() for arm (David Carlier)
  * linux: fix uv__accept4() (twosee)
  * win: handle file paths in uv_fs_statfs() (erw7)
  * unix: fix uv_os_environ() null pointer check (Rikard Falkeborn)
  * win: fix uv_os_environ() null pointer check (Rikard Falkeborn)
  * unix: fix compilation on macOS 32-bit architectures (Brad King)
  * win: replace alloca() with stack-based array (Ben Noordhuis)
v1.35.0
  * pipe: disallow listening on an IPC pipe (Witold Kręcicki)
  * unix: remove support for FreeBSD < 10 (Saúl Ibarra Corretgé)
  * linux: simplify uv__accept() (Ben Noordhuis)
  * linux: assume presence of SOCK_CLOEXEC flag (Ben Noordhuis)
  * linux: simplify uv__dup2_cloexec() (Ben Noordhuis)
  * freebsd,linux: simplify uv__make_socketpair() (Ben Noordhuis)
  * unix: fix error handling in uv__make_socketpair() (Ben Noordhuis)
  * freebsd,linux: simplify uv__make_pipe() (Ben Noordhuis)
  * unix: fix error handling in uv__make_pipe() (Ben Noordhuis)
  * linux: simplify uv__async_eventfd() (Ben Noordhuis)
  * linux: assume the presence of inotify system calls (Ben Noordhuis)
  * unix: make uv_tcp_keepalive predictable (Manuel BACHMANN)
  * unix: fix error path in uv_setup_args() (Ben Noordhuis)
  * unix: fix size check in uv_get_process_title() (Ben Noordhuis)
  * freebsd,linux: add recvmmsg() + sendmmsg() udp implementation (Marek
    Vavrusa)
  * win,pipe: ensure `req->event_handle` is defined (Elliot Saba)
  * win,pipe: consolidate overlapped initialization (Elliot Saba)
  * win,pipe: erase event_handle after deleting pointer (Jameson Nash)
  * unix: fix uv_cpu_info always returning UV_ENOTDIR on OpenBSD (Ben Davies)
  * win,tty: Change to restore cursor shape with uv_tty_reset() (erw7)
  * win,tty: Added set cursor style to CSI sequences (erw7)
  * unix: use socklen_t instead of size_t (Ben Noordhuis)
  * unix: fix signal handle closing deferral (Ben Noordhuis)