[WIP] upgrade libvterm  [skip ci]
Will currently fail to build:

    FAILED: src/nvim/CMakeFiles/nvim.dir/terminal.c.o
    /usr/local/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DUSE_GCOV -D_GNU_SOURCE -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I/usr/include/luajit-2.0 -isystem ../.deps/usr/include -Werror --coverage -g   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -MD -MT src/nvim/CMakeFiles/nvim.dir/terminal.c.o -MF src/nvim/CMakeFiles/nvim.dir/terminal.c.o.d -o src/nvim/CMakeFiles/nvim.dir/terminal.c.o   -c ../src/nvim/terminal.c
    ../src/nvim/terminal.c: In function ‘terminal_init’:
    ../src/nvim/terminal.c:177:12: error: ‘VTermColor’ {aka ‘union <anonymous>’} has no member named ‘red’
      177 |       color.red = 0;
          |            ^
    ../src/nvim/terminal.c:178:12: error: ‘VTermColor’ {aka ‘union <anonymous>’} has no member named ‘green’
      178 |       color.green = 0;
          |            ^
    ../src/nvim/terminal.c:179:12: error: ‘VTermColor’ {aka ‘union <anonymous>’} has no member named ‘blue’
      179 |       color.blue = (uint8_t)(color_index + 1);
          |            ^