build(win): failure due to pointer conversion
Problem:
Building with GCC fails with ninja: build stopped: subcommand failed.
This is a cmake build. Slightly above in the log I can see the message
neovim/src/nvim/tui/tui.c:391:21: error: passing argument 1 of 'os_tty_guess_term' \
  from incompatible pointer type [-Wincompatible-pointer-types]
This is on GCC 15.1.0 and MSYS2.

Solution:
The call to os_tty_guess_term seems to only be used behind define MSWIN,
it accepts a const char **. making term into a const pointer lets the
build succeed.