fix: add missing void as function argument
src/cjson/fpconv.c:205:6: error: old-style function definition
[-Werror=old-style-definition]
  205 | void fpconv_init()
      |      ^~~~~~~~~~~

See also https://fedoraproject.org/wiki/Changes/PortingToModernC

Signed-off-by: Andreas Schneider <asn@cryptomilk.org>