lua: suppress unused variable warning
Fails in OpenBSD build.

FAILED: src/nvim/CMakeFiles/nvim.dir/lua/executor.c.o
/usr/bin/cc -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -D_GNU_SOURCE -Dnvim_EXPORTS -Iconfig -I../src -Isrc/nvim/auto -Iinclude -I../.deps/usr/include/luajit-2.1 -isystem ../.deps/usr/include -isystem /usr/local/include -O2 -DNDEBUG   -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wno-c11-extensions -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -Werror -MD -MT src/nvim/CMakeFiles/nvim.dir/lua/executor.c.o -MF src/nvim/CMakeFiles/nvim.dir/lua/executor.c.o.d -o src/nvim/CMakeFiles/nvim.dir/lua/executor.c.o   -c ../src/nvim/lua/executor.c
../src/nvim/lua/executor.c:1408:7: error: unused variable 'top' [-Werror,-Wunused-variable]
  int top = lua_gettop(lstate);
      ^
1 error generated.

https://builds.sr.ht/~jmk/job/253669